services:
  - docker:19.03.7-dind

stages:
  - build
  - docker

maven build:
  image: maven:3.6.3-jdk-11-slim
  stage: build
  script:
    - mvn clean install && mvn package -B
  artifacts:
    paths:
      - target/*.jar

docker build:
  image: docker:stable
  stage: docker
  script:
    - docker build -t $DOCKER_REPO .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
    - docker push $DOCKER_REPO
