services:
  - docker:19.03.7-dind

stages:
  - build

maven build:
  image: maven:3.6.3-jdk-11-slim
  stage: build
  script:
    - mvn clean install && mvn package -B
  artifacts:
    paths:
      - target/*.jar
