services:
  - docker:19.03.7-dind

stages:
  - build
  - docker

maven-build:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: docker:20.10.8-dind-alpine3.13
  services:
    - docker:20.10.8-dind
  stage: build
  before_script:
    - apk add --update openjdk11
  script:
    - chmod 755 ./mvnw
    - ./mvnw spring-boot:build-image
    - ls target

docker build:
  image: docker:stable
  stage: docker
  script:
    - docker build -t $DOCKER_REPO .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
    - docker push $DOCKER_REPO
